### ISSUE TITLE
Dotnet Migrate crashes on OWIN dependencies

### ISSUE THREAD

**Issue by mbenua-mparticle** [dotnet/cli-migrate#45]
## Steps to reproduce
Attempting to migrate a solution that contains an xproj with a reference to OWIN causes the entire migration to crash. For reference, this is what the project.json looks like (and it functions and compiles perfectly fine on the xproj system):

```json
{
  "version": "1.0.0-*",
  "dependencies": {
    "AWSSDK.Core": "3.3.5",
    "AWSSDK.KeyManagementService": "3.3.1.1",
    "AWSSDK.S3": "3.3.1.2",
    "MP": "1.0.0-*",
    "Auth0.Core": "3.6.0",
    "Auth0.AuthenticationApi": "3.6.0",
    "Microsoft.Owin" : "3.0.1",
    "Microsoft.Owin.Security" :  "3.0.1",
    "Microsoft.Owin.Security.Jwt" :"3.0.1",
    "Microsoft.Owin.Security.OAuth" :"3.0.1" ,
    "Nancy" : "1.4.3",
    "Nancy.MSOwinSecurity" :  "1.0.1",
    "Nancy.Owin" :  "1.4.1",
    "Newtonsoft.Json" :"9.0.1",
    "System.IdentityModel.Tokens.Jwt": "4.0.0"    
  },
  "configurations": {
    "Release": {
      "buildOptions": {
        "optimize": true
      }
    }
  },
  "frameworks": {
    "net46": {
      "frameworkAssemblies": {
        "System": "",
        "System.Configuration": "",
        "System.Core": "",
        "System.Data": "",
        "System.Data.DataSetExtensions": "",
        "System.DirectoryServices": "",
        "System.Runtime.Serialization": "",
        "System.ServiceModel": "",
        "System.Xml": "",
        "System.Xml.Linq": "",
        "System.IdentityModel":"",
      }
    }
  }
}
```

The same error appears whether running dotnet migrate on the SLN file or directly in the directory of the problem proj, and whether it is done from the CLI or from within the UI in the latest version of VS2017.

I've seen this on at least one other project that also happens to reference that set of OWIN projects off nuget.

## Expected  behavior
Project should migrate to the csproj format with the appropriate references!

## Actual behavior
```
> dotnet migrate
Migration failed.

Unhandled Exception: System.ArgumentException: An item with the same key has already been added. Key: OWIN
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectContextBuilder.ScanLibraries(LockFileTarget target, LockFileLookup lockFileLookup, Dictionary`2 libraries, MSBuildDependencyProvider msbuildResolver, PackageDependencyProvider packageResolver, ProjectDependencyProvider projectResolver)
   at Microsoft.DotNet.Internal.ProjectModel.ProjectContextBuilder.Build()
   at Microsoft.DotNet.Internal.ProjectModel.ProjectContext.<CreateContextForEachFramework>d__45.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.ComputeMigrationRuleInputs(MigrationSettings migrationSettings)
   at Microsoft.DotNet.ProjectJsonMigration.ProjectMigrator.Migrate(MigrationSettings rootSettings, Boolean skipProjectReferences)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Execute()
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.<>c__DisplayClass35_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Migrate.MigrateCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

## Environment data
`dotnet --info` output:
> dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4

**Comment by mbenua-mparticle** [comment]
@livarcocc Is this the right place to be opening bugs like this? Thanks!
